name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -o hatena-blog-org-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o hatena-blog-org-linux-arm64 .
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -o hatena-blog-org-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o hatena-blog-org-darwin-arm64 .
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -o hatena-blog-org-windows-amd64.exe .

    - name: Create checksums
      run: |
        sha256sum hatena-blog-org-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hatena-blog-org-linux-amd64
          hatena-blog-org-linux-arm64
          hatena-blog-org-darwin-amd64
          hatena-blog-org-darwin-arm64
          hatena-blog-org-windows-amd64.exe
          checksums.txt
        body: |
          ## Changes
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
          
          ## Installation
          
          Download the appropriate binary for your platform and make it executable:
          
          ### Linux/macOS
          ```bash
          chmod +x hatena-blog-org-*
          sudo mv hatena-blog-org-* /usr/local/bin/hatena-blog-org
          ```
          
          ### Windows
          Add the executable to your PATH.
          
          ## Requirements
          
          - [pandoc](https://pandoc.org/installing.html) must be installed
          
          ## Usage
          
          ```bash
          hatena-blog-org -file article.org -id your-hatena-id -key your-api-key -domain your-blog-domain
          ```
          
          See [README.md](README.md) for detailed usage instructions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}